// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EspNamepop","status":false,"description":"Display the names of noted events on the top of them.","parameters":{}},
{"name":"EspAutoJump","status":false,"description":"Allow the player automaticly jump over small gaps.","parameters":{"SE Name":"","SE Volume":"100","SE Pitch":"100","SE Pan":"100"}},
{"name":"EspItemColor","status":false,"description":"Draw names of certain items with certain color.","parameters":{}},
{"name":"EspTextSE","status":false,"description":"Playing SE while showing text.","parameters":{"SE Name":"Key","SE Volume":"100","SE Pitch":"100","SE Pan":"100"}},
{"name":"EspPicButton","status":false,"description":"Unfinished.","parameters":{}},
{"name":"Tester","status":true,"description":"","parameters":{}}
];
